version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - my_network

  graphql:
    build: .
    container_name: graphql_service
    command: python /app/backend/graph_get_info.py
    ports:
      - "4000:4000"
    depends_on:
      - prometheus
    networks:
      - my_network

  alert:
    build: .
    container_name: alert_service
    command: python /app/backend/alert_endpoint.py
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - prometheus
    networks:
      - my_network

  metrics:
    build: .
    container_name: metrics_service
    command: python /app/backend/metrics.py
    ports:
      - "8000:8000"
    networks:
      - my_network

  frontend:
    image: nginx:alpine
    container_name: frontend_service
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
