global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'sensor_metrics'
    static_configs:
      - targets: ['metrics_service:8000']
